### ISSUE TITLE
Allow transpilation options to be provided to Qiskit devices

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/pennylane-qiskit#107]
The Qiskit `transpile` function accepts a wide range of options: https://qiskit.org/documentation/stubs/qiskit.compiler.transpile.html

We should allow keyword arguments to devices to be passed during transpilation.

This could be done by inspecting `qiskit.compiler.transpile`, and passing any keyword arguments that occur in the signature.

**Comment by sagarpahwa** [comment]
Hi @josh146 I am interested in working on this one. Can I give this one a try? 
I have worked on qiskit transpiler code earlier.

**Comment by josh146** [comment]
Hi @sagarpahwa, this would be a great first issue for a PR 🙂

**Comment by sagarpahwa** [comment]
Thank you @josh146, I will start working on it.

**Comment by josh146** [comment]
@sagarpahwa, feel free to make a PR to this repo titled `[WIP] Pass transpilation options`. If you run into any issues, feel free to ask

**Comment by co9olguy** [comment]
@sagarpahwa great! Looking forward to your contribution :smiley:

**Comment by sagarpahwa** [comment]
Hi @josh146 , @co9olguy 

I tried to understand the code and the required changes. PFB the understanding.

__File to change__: qiskit_device.py
__location__:
```
compiled_circuits = transpile(self._circuit, backend=compile_backend)
memory = str(compile_backend) not in self._state_backends
return assemble(
    experiments=compiled_circuits,
    backend=compile_backend,
    shots=self.shots,
    memory=memory,
)

```
__parameters to pass__: 

```
transpile_params = [
basis_gates,
coupling_map,
backend_properties,
initial_layout,
layout_method,
routing_method,
translation_method,
seed_transpiler,
optimization_level,
pass_manager,
callback,
output_name
]

assemble_params = [
qobj_id,
qobj_header,
max_credits,
seed_simulator,
qubit_lo_freq,
meas_lo_freq,
qubit_lo_range,
meas_lo_range,
schedule_los,
meas_level,
meas_return,
meas_map,
memory_slot_size,
rep_time,
rep_delay,
parameter_binds,
parametric_pulses,
init_qubits,
**run_config
]
```

- If my understanding is correct, then do we need to pass the additional parameters to both compile and assemble method?
- Also, these will be at root level of the **kwargs coming to apply method, or we need to nest them into separate sub-dictionaries?

**Comment by antalszava** [comment]
Hi @sagarpahwa :slightly_smiling_face: 

> If my understanding is correct, then do we need to pass the additional parameters to both compile and assemble method?

There might be distinct options for the `transpile` and the `assemble` functions. A first step could be wiring in options for the `transpile` function, as per the original idea. That solution could then be extended in a similar fashion for `assemble`. If there are keyword arguments that are accepted by both functions, I'd think it would be fine for now to pass the same value in both cases. :slightly_smiling_face: 

> Also, these will be at root level of the **kwargs coming to apply method, or we need to nest them into separate sub-dictionaries?

One approach here could be to create a `transpile_options` dictionary for the device. Valid options for `transpile` that are passed as keyword arguments when creating the `QiskitDevice` could then be added into this dictionary.

As @josh146 mentioned, using `inspect` to get the function arguments could lead to a nice solution. This would allow dynamically determining which are valid arguments (without having to keep track of them in a list) and could allow that no breaking changes are introduced to PennyLane-Qiskit even when the signature of `transpile` changes.

This would include obtaining the signature of `transpile` (and including the result in the logic):
```python
from qiskit.compiler import transpile
import inspect

res = inspect.signature(transpile)
```

A similar inspection is used for the `backend.run` method.

**Comment by sagarpahwa** [comment]
Thanks @antalszava for helping out.
I went back and checked the way we are passing the parameters to the run method.

1. ``` 
    s = inspect.signature(b.run)
    self.run_args = {}
    ```
2. ```
    if "noise_model" in kwargs:
        if "noise_model" in s.parameters:
            self.run_args["noise_model"] = kwargs.pop("noise_model")
    ```
3. ```
    if "backend_options" in s.parameters:
            self.run_args["backend_options"] = kwargs
    ```
With this, for qasm_simulator, a user is never able to pass this argument
- validate (bool) – validate the Qobj before running (default: True).

in general, 
    - user won't be able to pass any argument except noise_model, qobj, backend_options
    - all other args will be assed as part of backend_options 
    ``` 'backend_options': {'test_param': 'dummy_param', 'optimization_level': 3, 'validate': False, 'verbose': False} ```

My understanding is at stage 3 the code should be:
```
    if "backend_options" in s.parameters:
            self.run_args["backend_options"] = kwargs.pop("backend_options")
```
or even more, I think, we can do it in one go:
1. create argument setter utility function
```
    def set_args(source, signature, destination):
        for arg in signature:
            if arg in source:
                # don't pop args, as it might be common to run and compile
                self.destination[arg] = source[arg]
```
1. during init
```
    run_sig = inspect.signature(b.run)
    self.run_args = {}
    set_args(kwargs, run_sig, self.run_args)
    
    
    # if user passes transpile options at time of init
    transpile_sig = inspect.signature(transpile)
    self.transpile_args = {}
    set_args(kwargs, transpile_args, self.transpile_args)
    
```
2. during apply
```
    transpile_sig = inspect.signature(transpile)
    # no need to initialize transpile_args, only updte them if required
    set_args(kwargs, transpile_args, self.transpile_args)
```
As, this will be my first contribution to pennylane, let me know if I am missing out something important, or we should do it step by step (same as transpile and assemble changes)

**Comment by antalszava** [comment]
Hi @sagarpahwa,

The approach you've outlined looks good overall! The parsing and storing of transpile/assemble/run arguments can be further extended, as you've pointed out.

>      if "backend_options" in s.parameters:
>          self.run_args["backend_options"] = kwargs

The logic here assumes that everything that was further left in `kwargs` was meant to be passed `backend_options`.

As @josh146 mentioned, feel free to reach out if you'd have further questions or feel it would be good for us to go through the specific solution.

**Comment by sagarpahwa** [comment]
Thanks @antalszava for the review. I will do the rest of the changes.

@josh146 , It seems to me that run method argument passing needs a little amendment as well. but as discussed earlier I am making changes here only for transpiration options, assuming that we will track other changes (assemble and run) via separate threads. If everything here goes fine, would like to work upon the rest of the tasks.
