### ISSUE TITLE
Add support for returning job execution times

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane-qiskit#109]
We would like to allow retrieving the time taken for jobs when using IBMQ. This is at the moment not available, as results are obtained from the specific `Job` objects (e.g. counts) and neither the job objects nor result objects are stored explicitly. An approach could be to store internally the information contained in [`job.time_per_step`](https://qiskit.org/documentation/stubs/qiskit.providers.ibmq.job.IBMQJob.time_per_step.html) and `result.time_taken`.

For optimization tasks, it can be desirable to store multiple job execution times and not just the most recent.

Further details can be found in [this request](https://discuss.pennylane.ai/t/how-do-i-get-execution-time-of-jobs-not-transpile-queue-python-etc-time-on-qiskit-hardware/613).

**Comment by sagarpahwa** [comment]
Hi @antalszava, can I try to look into this one? Might need some help though.
Thanks in advance!

**Comment by antalszava** [comment]
Hi @sagarpahwa, that's great, thanks for showing interest there!

Definitely! This could be coming up after concluding with #108. Once merged we could explore what could be a nice approach here.

**Comment by sagarpahwa** [comment]
Okay, will start exploring the existing code meanwhile.

Thanks @antalszava .

**Comment by antalszava** [comment]
Hi @sagarpahwa, feel free to let us know if you'd need some help in terms of design or anything here

**Comment by sagarpahwa** [comment]
Oh, my bad. Forgot to provide update here. exams are going on right now, won't be able to work till 2nd November.

If possible, can I start this post that?

**Comment by antalszava** [comment]
Hi @sagarpahwa, no worries! Sure, starting then works fine too.

Good luck with your exams! :slightly_smiling_face:

**Comment by albi3ro** [comment]
I'd like to revive this issue, as it ties in well with the addition of the [Tracker](https://pennylane.readthedocs.io/en/latest/code/api/pennylane.Tracker.html) in PennyLane v0.17.0 .
