### ISSUE TITLE
Circular import

### ISSUE THREAD

**Issue by mickahell** [PennyLaneAI/pennylane-qiskit#123]
**Describe the bug**
When I want to use the qiskit.aer or qiskit.basicaer backend I have this error :
`AttributeError: partially initialized module 'pennylane_qiskit' has no attribute 'AerDevice' (most likely due to a circular import)`

**My code :**
```
import pennylane as qml
dev1 = qml.device("qiskit.aer", wires=4)
```

**Desktop :**
 - OS: Mac OS bigSUR
 - Python 3.8.1
 - Pennylane version : 0.13
 - Pennylane Qiskit version : 0.13

**Comment by antalszava** [comment]
Hi @mickahell, thank you for the report! :slightly_smiling_face: 

It sounds odd! :thinking: Does the error appear even when trying in a completely new environment (when installing PennyLane and PennyLane-Qiskit form scratch)?

Also, could there be any additional local files with the name `pennylane_qiskit` that might be mistaken as a Python module?

**Comment by mickahell** [comment]
@antalszava oh I just find it because of you, The problem was my name file, I named my file pennylane_qiskit.py so I renamed it planne_qiskit.py and that works now.

Thanks for your help :)
