### ISSUE TITLE
Support loading Parameter Expressions

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane-qiskit#129]
Currently, the `load` function to convert a Qiskit circuit cannot convert Qiskit `ParameterExpression`'s with more than a simple, unaltered `Parameter`.  See error raised at [converter.py#L205](https://github.com/PennyLaneAI/pennylane-qiskit/blob/059964d097e14e5c1b36d231ec5b4330a4e345f5/pennylane_qiskit/converter.py#L205)

PennyLane now, as of v0.14.0, supports classical processing of arguments within a circuit.  With this change, PennyLane-Qiskit should update their support of `ParameterExpression`'s.  

We should be able to do the following:

```python
from qiskit import QuantumCircuit
from qiskit.circuit import Parameter
from pennylane_qiskit import load

a = Parameter("a")
b = Parameter("b")

qc = QuantumCircuit(1,1)
qc.rz(a*b, [0])

circ = load(qc)(params={a: 0.1, b: 0.1})
```

## Potential Solution

`ParameterExpression`'s are based on SymPy, and thus we can use SymPy functions with them.  

```python
from sympy import lambdify

expr = a*b
f = lambdify([a,b], expr, 'numpy')
f(0.1, 0.1)
```

The resulting function is differentiable in pennylane:

```
import pennylane as qml

qml.grad(f)(1.0, 1.0)
```

**Comment by antalszava** [comment]
@albi3ro has this been resolved?

**Comment by lillian542** [comment]
This is supported now - for example, we can do:

```
from qiskit import QuantumCircuit
from qiskit.circuit import Parameter
from pennylane_qiskit import load

dev = qml.device("default.qubit")

a = Parameter("a")
b = Parameter("b")

qc = QuantumCircuit(1,1)
qc.rx(a*b, [0])

@qml.qnode(dev)
def circuit(x, y):
    load(qc)(params={a: x, b: y})
    return qml.expval(qml.PauliZ(0))
```
and run

```
>>> circuit(0, np.pi)
tensor(1., requires_grad=True)

>>> circuit(1, np.pi)
tensor(-1., requires_grad=True)

>>> circuit(0.5, np.pi)
tensor(2.22044605e-16, requires_grad=True)
```
    
The circuit is differentiable.
