### ISSUE TITLE
QCGPU support

### ISSUE THREAD

**Issue by ycchen1989** [PennyLaneAI/pennylane-qiskit#24]
**Is your feature request related to a problem? Please describe.**

Thanks to the author for providing this plugin. I am wondering whether it is possible to 
use this plugin with GPU-acclerated or parallel computation for simulation.

**Describe the solution you'd like**

For the GPU-acclerated, it has already a plugin for Qiskit.
https://github.com/Qiskit/qiskit-qcgpu-provider

For the parallel computation, qiskit has already provided it.
https://qiskit.org/documentation/terra/terra_parallel_tools.html

**Describe alternatives you've considered**

I am wondering if it is possible to use these existing solutions?

**Additional context**

**Comment by carstenblank** [comment]
This is an interesting question. I think adding the GPU-accelerated provider shouldn't be a difficult task. I don't know if I will be able to address this any time soon.

**Comment by mariaschuld** [comment]
I am closing this for now, feel free to re-open if needed.
