### ISSUE TITLE
websocket warning

### ISSUE THREAD

**Issue by phil333** [PennyLaneAI/pennylane-qiskit#261]
I keep getting the following warning over and over again, and the job doesn't properly connect to ibmq
WARNING::websocket:websocket connected

**Comment by CatalinaAlbornoz** [comment]
Hi @phil333,

This warning actually indicates that the connection to IBMQ was successful. Could you please add some more details on what you're trying to run or the error message that you're getting after the warning?

**Comment by phil333** [comment]
Problem solved, looks like a dependency issues. I reinstalled the machine and it just worked. It might have been that I ran `pip install -r requirements.txt`
