### ISSUE TITLE
IndexError: list index out of range when checking states[i] != i

### ISSUE THREAD

**Issue by EelVex** [PennyLaneAI/pennylane-qiskit#266]
This line: https://github.com/EelVex/pennylane-qiskit/blob/e84c57c96ff993894fbb0007af26dd9f4c1d0658/pennylane_qiskit/runtime_devices.py#L219
will trigger an `IndexError` if the `number_of_states-1` is not in `states`.

**Comment by CatalinaAlbornoz** [comment]
Hi @EelVex, thank you very much for opening this issue! Would you like to open a PR with a proposed fix? Or do you have additional thoughts or ideas for a fix?

**Comment by EelVex** [comment]
Hi @CatalinaAlbornoz . I have submitted PR#267 that fixes this issue.

**Comment by CatalinaAlbornoz** [comment]
Awesome. That's great @EelVex !
