### ISSUE TITLE
Migrate to Qiskit 1.0

### ISSUE THREAD

**Issue by frankharkins** [PennyLaneAI/pennylane-qiskit#512]
**Is your feature request related to a problem? Please describe.**

I'm making this issue because this project is part of the [Qiskit ecosystem](https://qiskit.github.io/ecosystem/).

As of June 2024, we're introducing a requirement that all projects are compatible with Qiskit 1.0. New users will be using Qiskit 1.0 and we want to make sure any projects we guide them to work straight away.

In June, we will test out your project and remove it if it doesn't work with Qiskit 1.0. This includes cases in which we can't get the project working because the documentation is lacking. We do value your project so let me know if you need any help migrating or have any other concerns.

**Describe the solution you'd like**

Migrate to Qiskit 1.0

**Describe alternatives you've considered**

N/A

**Additional context**

See our [migration guide](https://docs.quantum.ibm.com/api/migration-guides). and let me know if you need any support (such as answering questions about Qiskit or code review). With Qiskit's new stability policy, this should be the last change needed for a while.

**Comment by frankharkins** [comment]
Just seen https://github.com/PennyLaneAI/pennylane-qiskit/pull/508; does this mean the project already works with Qiskit 1.0? If so, apologies!

**Comment by trbromley** [comment]
Thanks @frankharkins. The most recent release of the PennyLane-Qiskit plugin had partial compatibility with Qiskit - where circuit conversion was supported but we had some issues with integrating with remote backends.

Our objective is to have full Qiskit 1.0 support in the next release in a few week's time. Though if you spot any issues when you come to test things in June, it'd be great if you could let us know.
